server:
    port: 0

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      host: localhost
      port: 27017
      database: arsdb
  application:
    name: booking-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/